### ISSUE TITLE
Draw more attention to the "Edit Page" button

### ISSUE THREAD

**Issue by MrKarlDilkington** [concrete5/documentation.concrete5.org#15]
By adding a pencil icon, changing the Bootstrap button class, and bolding some text, we can make the "Edit Page" button stand out more to encourage more contributions.

### Current:

![image](https://user-images.githubusercontent.com/10898145/58826379-93de6300-860e-11e9-98d3-594fcf5567a0.png)

### Proposed Changes:

![image](https://user-images.githubusercontent.com/10898145/58826397-9e98f800-860e-11e9-8db2-6f666e8bb04a.png)

**Comment by mesparza5** [comment]
Thank you @MrKarlDilkington we just created a PR with your suggestion 👍

**Comment by MrKarlDilkington** [comment]
@mesparza5 

No thank you, I am very excited about all this new documentation related activity.

# I :heart: documentation!
