### ISSUE TITLE
Make "Edit Page" visible for everyone

### ISSUE THREAD

**Issue by MrKarlDilkington** [concrete5/documentation.concrete5.org#8]
Idea from @mlocati.

Currently the "Edit Page" button is visible for logged in users, but hidden for guests. The proposed change is making this button visible for everyone,

Few community members are aware that they can add/edit/update documentation. A visible "Edit Page" button would increase awareness and the number of people contributing.

**Current:**

![image](https://user-images.githubusercontent.com/10898145/46223385-42643280-c321-11e8-97c9-ee0afbf11487.png)

**Proposed Changes:**

![image](https://user-images.githubusercontent.com/10898145/46223397-485a1380-c321-11e8-8c5d-72c06dc5bb46.png)

@wordish may have submitted a change for this already. If so, I will close this issue.

**Comment by aembler** [comment]
Makes sense.

**Comment by a3020** [comment]
I was looking at @mlocati's PR https://github.com/concrete5/documentation.concrete5.org/pull/12, but wouldn't it make more sense to **move the "Edit Page" to the top of the sidebar** instead of the bottom? 

E.g. take this doc page: https://documentation.concrete5.org/developers/concepts/front-end-content. If the Edit button is all the way at the bottom, it may not be visible enough. I think.

**Comment by mlocati** [comment]
IMHO the contents is more relevant than the edit button.
Furthermore if you browse other pages of the docs site you may notice that Edit button

**Comment by a3020** [comment]
E.g. [Symfony](https://symfony.com/doc/current/setup.html) has an edit button on top of the doc page. I think it makes sense, especially because our documentation is far from perfect and we want to maximize the number of edits. Another advantage is that the link will always be in the same place.

**Comment by mlocati** [comment]
In #12 I also added a "contribute" link on the top bar

**Comment by JohntheFish** [comment]
When editing a site, the dashboard bar with edit and everything is across the top of the page. Putting the docs edit button at the top would be more consistent with that and open up the scope for further dashboard style functionality once we have continuity of sticky login between c5.org and docs. For example, a quick list of 'My recent changes' with approval status. Such a dashboard bar could then be standardised to the re-worked c5.org.

**Comment by wordish** [comment]
Finally deployed correctly! Thanks!

**Comment by MrKarlDilkington** [comment]
@wordish 

Exellent, thank you.

**Comment by mlocati** [comment]
Great, very handy!
